### ISSUE TITLE
Warning: commit #23 has rolled back some translations

### ISSUE THREAD

**Issue by richoux** [ourjapanlife/findadoc-localization#56]
I saw that commit #23 (7099d874775890c9811a37861e6075f9a2e084ac) has changed some translations into their older states. This is the case for the French translation, where my contributions have been lost in the process, and some other translations may have been impacted. Just to warn you!

**Comment by ann-kilzer** [comment]
Thanks for filing, I made a mistake with the localization tool. We should look into this more.

**Comment by ann-kilzer** [comment]
The fixes have been updated on the main site. Give it five minutes to build. Thanks again for the nudge @richoux and please open an issue or make corrections if you see future opportunities. 🙇🏻‍♀️
